# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '8.0'

target 'GWCommonTest' do
  
    use_frameworks!

    pod 'SnapKit'

end
